-- ══════════════════════════════════════════════════════════════
--  FinTech Fraud Detection — PostgreSQL Schema Initialisation
--  Runs automatically on first container start
-- ══════════════════════════════════════════════════════════════

-- ── Raw transactions (all ingressed records) ──────────────────
CREATE TABLE IF NOT EXISTS transactions (
    id                  SERIAL PRIMARY KEY,
    user_id             VARCHAR(20)     NOT NULL,
    event_timestamp     TIMESTAMPTZ     NOT NULL,
    merchant_category   VARCHAR(50)     NOT NULL,
    amount              NUMERIC(12, 2)  NOT NULL,
    location_country    VARCHAR(60)     NOT NULL,
    location_city       VARCHAR(60)     NOT NULL,
    is_fraud            BOOLEAN         DEFAULT FALSE,
    fraud_reason        VARCHAR(120),
    ingested_at         TIMESTAMPTZ     DEFAULT NOW()
);

-- ── Fraud alerts (flagged records only) ───────────────────────
CREATE TABLE IF NOT EXISTS fraud_alerts (
    id                  SERIAL PRIMARY KEY,
    user_id             VARCHAR(20)     NOT NULL,
    event_timestamp     TIMESTAMPTZ     NOT NULL,
    merchant_category   VARCHAR(50)     NOT NULL,
    amount              NUMERIC(12, 2)  NOT NULL,
    location_country    VARCHAR(60)     NOT NULL,
    location_city       VARCHAR(60)     NOT NULL,
    fraud_reason        VARCHAR(120)    NOT NULL,
    alert_generated_at  TIMESTAMPTZ     DEFAULT NOW()
);

-- ── Reconciliation reports (generated by Airflow every 6h) ───
CREATE TABLE IF NOT EXISTS reconciliation_reports (
    id                      SERIAL PRIMARY KEY,
    report_window_start     TIMESTAMPTZ     NOT NULL,
    report_window_end       TIMESTAMPTZ     NOT NULL,
    total_transactions      INTEGER         NOT NULL,
    total_ingress_amount    NUMERIC(15, 2)  NOT NULL,
    fraud_count             INTEGER         NOT NULL,
    fraud_amount            NUMERIC(15, 2)  NOT NULL,
    validated_count         INTEGER         NOT NULL,
    validated_amount        NUMERIC(15, 2)  NOT NULL,
    fraud_rate_pct          NUMERIC(6, 2)   NOT NULL,
    generated_at            TIMESTAMPTZ     DEFAULT NOW()
);

-- ── Fraud summary by merchant category (analytic report) ─────
CREATE TABLE IF NOT EXISTS fraud_by_merchant (
    id                  SERIAL PRIMARY KEY,
    report_date         DATE            NOT NULL,
    merchant_category   VARCHAR(50)     NOT NULL,
    fraud_count         INTEGER         NOT NULL,
    total_fraud_amount  NUMERIC(15, 2)  NOT NULL,
    UNIQUE (report_date, merchant_category)
);

-- ── Indexes for query performance ─────────────────────────────
CREATE INDEX IF NOT EXISTS idx_txn_user_time       ON transactions (user_id, event_timestamp);
CREATE INDEX IF NOT EXISTS idx_txn_fraud           ON transactions (is_fraud);
CREATE INDEX IF NOT EXISTS idx_alerts_user_time    ON fraud_alerts (user_id, alert_generated_at);
CREATE INDEX IF NOT EXISTS idx_recon_window        ON reconciliation_reports (report_window_start);

-- ── Seed: merchant categories (reference) ─────────────────────
CREATE TABLE IF NOT EXISTS merchant_categories (
    code        VARCHAR(50) PRIMARY KEY,
    description VARCHAR(120)
);

INSERT INTO merchant_categories (code, description) VALUES
    ('grocery',         'Supermarkets and grocery stores'),
    ('electronics',     'Electronics and tech gadgets'),
    ('travel',          'Airlines, hotels, and travel agencies'),
    ('restaurant',      'Restaurants and food delivery'),
    ('online_retail',   'E-commerce and online marketplaces'),
    ('entertainment',   'Streaming, gaming, and events'),
    ('fuel',            'Petrol stations and fuel'),
    ('healthcare',      'Pharmacies and medical services'),
    ('luxury',          'Jewellery, watches, and high-end fashion'),
    ('atm_cash',        'ATM withdrawals and cash advances')
ON CONFLICT DO NOTHING;

-- ── Confirmation ──────────────────────────────────────────────
DO $$
BEGIN
    RAISE NOTICE '✅  fraud_detection schema initialised successfully.';
END $$;
